@startuml
skinparam componentStyle rectangle
node "Kafka (KRaft)" as Kafka {
  queue "events (Avro)" as T1
  queue "devices" as T2
}

node "Schema Registry" as SR
database "ClickHouse" as CH
node "Redis" as R

rectangle "events-collector-service" as ECS {
  [KafkaListener] as KL
  [EventProcessor] as EP
  [OutboxScheduler] as OS
  [KafkaProducer] as KP
}
T1 --> KL : consume
KL --> SR : fetch schema
EP --> CH : insert device_events
EP --> R : SADD devices:seen
EP --> CH : insert device_outbox (NEW)
OS --> R : lock outbox:lock (NX PX)
OS --> CH : select outbox NEW ...
OS --> KP : publish device_id ...
KP --> T2 : produce
OS --> CH : mark SENT ...
@enduml
