server:
  port: 8080

spring:
  application:
    name: events-collector-service

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}

    consumer:
      group-id: events-collector-group
      enable-auto-commit: false
      max-poll-records: 1
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        specific.avro.reader: true
        schema.registry.url: ${SCHEMA_REGISTRY_URL:http://localhost:8081}
      topic:
        name: events
        partitionCount: 3

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      topic:
        name: devices
        partitionCount: 3

    listener:
      ack-mode: manual
      concurrency: 1

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

  datasource:
    url: jdbc:clickhouse://${CLICKHOUSE_HOST:localhost}:8123/events
    username: ${CLICKHOUSE_USER:default}
    password: ${CLICKHOUSE_PASSWORD:}
    driver-class-name: com.clickhouse.jdbc.ClickHouseDriver

  scheduling:
    outboxCron: ${SCHEDULING_OUTBOX_CRON:0 * * * * *}
    batchSize: 10

  redis:
    lock-time-in-seconds: 10
    lock-key: outbox:lock
    publish-key: devices:published

management:
  endpoints:
    web:
      exposure:
        include: metrics, health, prometheus