{
 "title": "Events Collector Dashboard",
 "tags": [ "events-collector" ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Events Ingested",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "targets": [
    { "expr": "events_ingested_total" }
   ]
  },
  {
   "title": "Outbox Created",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "targets": [
    { "expr": "outbox_saved_total" }
   ]
  },
  {
   "title": "Devices Published",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "targets": [
    { "expr": "devices_published_total" }
   ]
  },
  {
   "title": "Publish Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "targets": [
    { "expr": "devices_publish_errors_total" }
   ]
  }
 ]
}